include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_catches_without_on_clauses: false
    no_default_cases: false
    one_member_abstracts: false
    avoid_classes_with_only_static_members: false
analyzer:
  exclude:
    - "**/*.g.dart"
